spring:
  application:
    name: mcp-server-database

  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    banner-mode: off
    web-application-type: none

  # 数据源配置
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource

    # HikariCP 连接池配置（推荐）
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: HikariPool-PostgreSQL

logging:
  pattern:
    console:
  file:
    name: ${spring.application.name}.log

# MyBatis 配置
mybatis:
  # mapper.xml 文件位置
  mapper-locations: classpath:mappers/*.xml
  # 实体类别名包路径
  # 配置映射器
  configuration:
    map-underscore-to-camel-case: true  # 自动将下划线命名转换为驼峰命名
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

csdn:
  api:
    cookie: "uuid_tt_dd=10_19015963630-1750143800631-176219; fid=20_21610282401-1750143801689-958452; UserName=qq_60413090; UserInfo=b204c2d9c57545a9b5ede5df99d056a2; UserToken=b204c2d9c57545a9b5ede5df99d056a2; UserNick=guxx325; AU=499; UN=qq_60413090; BT=1751337645514; p_uid=U010000; csdn_newcert_qq_60413090=1; tfstk=gXOxK9qPs0mc23OArEkujMyPk20otYY42n8QsGj0C3KJ7hF0i1fcCNsJbSAMSF9T6eSziEADSgI9j31i7xoqXrRJv5Vm0x8_61fsxDcntEuV_1iHUudubi7wPGglhHEtWX1sxDcotE8V_1tMid5reUsPWN_f5h6SNg7Nf1sfCuw5Rg111N6_Pz_Ckr_fchTSyNS5f116fUgR7jW-Xgafj5pnZkI1xNS815ORlcSBkgQPzQQAHMGF25TvwZBAAEOKboelPQARKT4iq_TeEn_R9jEFkLTdGNdZRRIOBI5R2HhQ_aJXDQ69ZVlprsQOd16855TR1K-e16GQ2aJWodO2DPF1uIAhBMW-55WGNBXBdnUZ8U1f5hWesDPVcFTeTpfKMk7vFeCR4jAH9iTYxMQgh438QRWfzbMQO0A8LPt1yM0x6RyNU47Rx438QRWfzaInkVeaQTuP.; FCNEC=%5B%5B%22AKsRol-GgnEZaG1xEcV2bspqz14svqx5CAedhv7DNqrDcUTSFNps-xVdiowQE_lAd2pG-6dzOnHwV4CztFhHW028JckWG3tSLntiSh4G1vg7EsJBYMmDcu5UIfDxkQ5P30iI18YTTg86I1XMgNUVC2PNk6Idz5cUrg%3D%3D%22%5D%5D; c_first_ref=www.bing.com; c_first_page=https%3A//www.csdn.net/; c_segment=11; Hm_lvt_6bcd52f51e9b3dce32bec4a3997715ac=1756437644,1756696170,1756777552,1756870890; HMACCOUNT=C865D62C6E610C23; c_ab_test=1; dc_sid=c5942a69f13bf05df31d7f22643dff48; _clck=cp292p%5E2%5Efz0%5E0%5E1994; dc_session_id=10_1756878501069.545236; c_dsid=11_1756878927227.803107; c-sidebar-collapse=0; creativeSetApiNew=%7B%22toolbarImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20231011044944.png%22%2C%22publishSuccessImg%22%3A%22https%3A//img-home.csdnimg.cn/images/20240229024608.png%22%2C%22articleNum%22%3A0%2C%22type%22%3A0%2C%22oldUser%22%3Afalse%2C%22useSeven%22%3Atrue%2C%22oldFullVersion%22%3Afalse%2C%22userName%22%3A%22qq_60413090%22%7D; __gads=ID=09ec45ca3b841533:T=1750149696:RT=1756881815:S=ALNI_MbMNPiVHHhmnt0_usGiXXKMndJc9Q; __gpi=UID=00001130f8737673:T=1750149696:RT=1756881815:S=ALNI_MaotMQRMx7bBesazg9abUyIjQMvDg; __eoi=ID=6308387afec28438:T=1750149696:RT=1756881815:S=AA-AfjYDCgyZXIimSvEukOBL3oRQ; toolbar_remind_num=1; _clsk=1wwoe1i%5E1756881861977%5E3%5E0%5Ek.clarity.ms%2Fcollect; c_pref=https%3A//mp.csdn.net/mp_blog/manage/article%3Fspm%3D1011.2124.3001.10336; c_ref=https%3A//mp.csdn.net/; c_page_id=default; Hm_lpvt_6bcd52f51e9b3dce32bec4a3997715ac=1756882079; log_Id_pv=37; log_Id_view=579; dc_tos=t202w9; log_Id_click=55"
    categories: "Java,Spring,后端"